[project]
requires-python = ">=3.7.1,<3.11"
dependencies = [
    "requests @ git+https://github.com/psf/requests.git@v2.25.0",
    "pandas>=1.2.5,<2"
]

[tool.pdm.dev-dependencies]
test = [
    "pytest~=5.2"
]
