# Read the Docs configuration file for MkDocs projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - python3-venv
  jobs:
    post_system_dependencies:
      # Install PDM
      - asdf plugin add pdm
      - asdf install pdm latest
      - asdf global pdm latest
      - pdm --version
    pre_install:
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH pdm install -dG doc

mkdocs:
  configuration: mkdocs.yml
