- Add new option `-g/--global` to manage global project. The default location is at `~/.pdm/global-project`.
- Use the virtualenv interpreter when detected inside an activated venv.
- Add new option `-p/--project` to select project root other than the default one.
